export const listaDePalavras = [
    { categoryTitle: 'Comidas',
    categoryList: ["Arroz", "Bife", "Frango", "Macarrão", "Lasanha", "Pizza", "Hambúrguer", "Peixe", "Salada", "Empada", "Torta", "Cupcake", "Pão de Queijo", "Churrasco", "Feijão", "Açaí", "Feijoada", "Espaguete", "Esfiha", "Strogonoff", "Moqueca", "Baião de Dois", "Cachorro Quente", "Espetinho", "Salgado", "Pudim", "Frutas", "Sopa", "Caldo", "Risoto", "Sanduíche", "Curry", "Tacos", "Brigadeiro", "Pão de Forma", "Nhoque", "Tapioca", "Arroz Integral", "Sushi", "Sashimi", "Torta de Limão", "Torta de Morango", "Pão de Batata", "Salada de Frutas", "Sopa de Legumes", "Sopa de Macarrão", "Canja de Galinha", "Guacamole", "Bolinho de Bacalhau", "Feijão Tropeiro", "Escondidinho", "Bolinho de Chuva", "Bolo de Rolo", "Pão de Mel", "Empanada", "Ceviche", "Tortilla", "Pão na Chapa", "Torta Holandesa", "Quesadilla", "Empadão", "Torta Alemã", "Fondue", "Ratatouille", "Ravioli", "Canelone", "Crepe", "Quiche", "Paella", "Kebab", "Falafel", "Tabule", "Empanadas", "Parmegiana", "Barbecue", "Vatapá"],
    },
    { categoryTitle: 'Lugares',
      categoryList: ["Brasil", "Estados Unidos", "China", "Rússia", "Japão","Alemanha", "Reino Unido", "França", "Itália", "Espanha","Canadá", "Austrália", "África do Sul", "Argentina", "México","Coréia do Sul", "Indonésia", "Países Baixos", "Tailândia", "Filipinas","Malásia", "Vietnã", "Irã", "Índia", "Rússia","Turquia", "Suécia", "Noruega", "Dinamarca", "Finlândia","Áustria", "Nova Zelândia", "Emirados Árabes Unidos", "Arábia Saudita", "Cingapura","Vaticano", "Israel", "Síria", "Líbano", "Iraque","Paquistão", "Catar", "Holanda", "Austrália", "Argentina","Uruguai", "Paraguai", "Colômbia", "Peru", "Chile","Equador", "Venezuela", "Bolívia", "México","São Paulo", "Rio de Janeiro", "Belo Horizonte", "Brasília", "Salvador","Fortaleza", "Manaus", "Recife", "Belém", "Goiânia","Curitiba", "Porto Alegre", "Ribeirão Preto", "São José dos Campos", "Campinas","Lisboa", "Madri", "Paris", "Berlim", "Roma","Moscou", "Tóquio", "Seul", "Pequim", "Cidade do México", "Cairo", "Istambul", "Barcelona"]
    },
    { categoryTitle: 'Objetos',
    categoryList: ["Teclado", "Mouse", "Celular", "Tablet", "Smartphone", "Carregador", "Fone de Ouvido", "Guitarra", "Piano", "Microfone", "Câmera", "Laptop", "Relógio", "Chave", "Caderno", "Caneta", "Lapiseira", "Borracha", "Tesoura", "Cola", "Papel", "Bloco", "Caderno de Desenho", "Lapiseira de Cor", "Quadro Branco", "Giz de Cera", "Sombrinha", "Pilha", "Telefone", "Alarme", "Ventilador", "Lâmpada", "Máquina de Lavar Roupa", "Secador de Cabelo", "Liquidificador", "Batedeira", "Fogão", "Forno", "Microondas", "Tábua de Passar", "Ferro de Passar", "Aspirador de Pó", "Gameboy", "Super Nintendo", "Xbox", "Playstation", "Televisão", "Home Theater", "Câmera de Segurança", "Termômetro", "Balança", "Relógio de Pulso", "Maquiagem", "Perfume", "Livro", "Quadro", "Pôster", "Adesivo", "Abajur", "Porta Retrato", "Vaso", "Planta", "Quadro Negro", "Pulseira", "Colar", "Brinco", "Anel", "Despertador", "Ventilador de Teto", "Projetor", "Data Show", "Luva", "Meia", "Guarda-Chuva", "Boné", "Óculos de Sol", "Bolsa", "Carteira", "Cinto", "Sapato", "Tênis", "Chapéu", "Cachecol", "Lenço", "Blusa", "Camisa", "Calça", "Short", "Drone", "Impressora 3D",  "Robô Aspirador", "Controle Remoto Universal", "Placa Mãe", "Processador", "Placa de Vídeo", "Fonte"],
    },
    { categoryTitle: 'Emoções',
    categoryList: ["Alegria", "Amor", "Ansiedade", "Apatia", "Borboleta no Estômago", "Cansaço", "Choque", "Compaixão", "Confiança", "Coragem", "Culpa", "Curiosidade", "Depressão", "Desânimo", "Desapontamento", "Desespero", "Dúvida", "Entusiasmo", "Estresse", "Excitação", "Felicidade", "Gratidão", "Irritação", "Medo", "Melancolia", "Nostalgia", "Optimismo", "Orgulho", "Pacificação", "Paixão", "Pânico", "Preocupação", "Raiva", "Reflexão", "Arrependimento", "Remorso", "Renovação", "Resignação", "Saudade", "Traição", "Vingança", "Serenidade", "Supresa", "Temor", "Tristeza", "Vergonha"],
    },

    { categoryTitle: 'Personalidades famosas',
    categoryList: ["Michael Jackson", "Elvis Presley", "Madonna", "Beyoncé", "Lionel Messi", "Cristiano Ronaldo", "Neymar", "Pelé", "Diego Maradona", "Kylian Mbappé",  "Steve Jobs", "Mark Zuckerberg", "Bill Gates", "Kim Kardashian", "Taylor Swift", "Rihanna", "Lady Gaga", "Justin Bieber",  "Will Smith", "Tom Cruise", "Leonardo DiCaprio", "Brad Pitt", "Meryl Streep", "Emma Watson", "Daniel Radcliffe", "Fernanda Montenegro", "Glória Pires", "Regina Casé", "Marieta Severo",  "Cláudia Raia", "Fátima Bernardes", "Ivete Sangalo", "Gugu", "Faustão", "Gil do Vigor", "Juliette", "Marília Mendonça", "Ana Maria Braga", "Sabrina Sato", "Luciano Huck", "Tom Hanks", "Papa Francisco", "Padre do Balão", "Lula", "Fernando Henrique Cardoso", "Dilma Rousseff", "João Doria", "Aécio Neves", "Sérgio Moro", "José Serra", "Eduardo Bolsonaro", "Sérgio Reis", "Paulo Maluf", "Geraldo Alckmin", "Padre Marcelo Rossi", "Padre Fábio de Melo", "Bispo Edir Macedo", "Silvio Santos", "Carla Diaz", "Valeska Popozuda", "Anitta", "Ludmilla", "Luisa Sonza", ],
    },

    { categoryTitle: 'Verbos',
    categoryList: ["Andar", "Correr", "Pular", "Brincar", "Beber", "Comer", "Escrever", "Ler", "Dormir", "Sentar", "Dizer", "Ver", "Ouvir", "Sentir", "Pensar", "Amor", "Ajudar", "Comprar", "Vender", "Pintar", "Cantar", "Dançar", "Desenhar", "Viajar", "Cozinhar", "Dirigir", "Jogar", "Trabalhar", "Estudar", "Ler", "Escutar", "Desejar", "Esperar", "Precisar", "Querer", "Sentir", "Tentar", "Testar", "Usar", "Verificar", "Visitar", "Esquecer", "Lembrar", "Amarrar", "Destravar", "Ligar", "Desligar", "Conectar", "Desconectar", "Abraçar", "Beijar", "Pegar", "Soltar", "Pousar", "Voar", "Nadar", "Mergulhar", "Pescar", "Caminhar", "Cortar", "Coletar", "Plantar", "Colher", "Cultivar", "Construir", "Destruir", "Fazer", "Tomar", "Procurar", "Encontrar", "Perder", "Ganhar", "Levantar", "Deitar", "Sentir-se", "Ficar", "Ir", "Vir", "Enviar", "Receber", "Assistir", "Aprender", "Ensinar", "Compreender", "Ignorar", "Aproveitar", "Desfrutar", "Adquirir", "Perder", "Roubar", "Comemorar", "Lamentar", "Alegrar-se", "Chorar", "Celebrar", "Lutar", "Vencer", "Derrotar", "Escapar", "Preso", "Escape", "Esconder", "Encontrar", "Procurar", "Alcançar", "Perseguir", "Escapar", "Proteger", "Salvar", "Atacar", "Defender", "Assediar", "Esperar", "Fugir", "Preservar", "Destruir", "Criar", "Modificar", "Manter", "Melhorar", "Piorar", "Transformar", "Operar", "Funcionar", "Quebrar", "Arrumar", "Consertar", "Montar", "Desmontar", "Capturar", "Libertar", "Suportar", "Agüentar", "Resistir", "Rendr-se", "Vencer", "Perder"],
    },    
    
    { categoryTitle: 'Filmes e Séries',
    categoryList: ["O Poderoso Chefão", "O Cavaleiro das Trevas", "Pulp Fiction", "O Senhor dos Anéis", "De Volta para o Futuro", "Star Wars", "Titanic", "Matrix", "Interestelar", "Clube da Luta", "Forrest Gump", "A Vida é Bela", "A Lista de Schindler", "Titanic", "Jurassic Park", "Indiana Jones", "E.T. - O Extraterrestre", "A Era do Gelo", "Os Incríveis", "Os Vingadores", "Shrek", "Toy Story", "Harry Potter e a Pedra Filosofal", "Ratatouille", "Aladdin", "Procurando Nemo", "A Bela e a Fera", "O Rei Leão", "Frozen", "Vingadores", "Jogos Vorazes", "O Labirinto do Fauno", "Náufrago", "O Exorcista", "X-Men", "Capitão América", "Cidade de Deus", "Velozes e Furiosos", "Auto da Compadecida", "Friends", "Breaking Bad", "The Sopranos", "The Simpsons", "Game of Thrones", "The Walking Dead", "The Big Bang Theory", "Stranger Things", "The Office", "Westworld", "House of Cards", "Narcos", "Black Mirror", "Orange is the New Black", "Lost", "The Crown", "Mad Men", "The Handmaid's Tale", "The Umbrella Academy", "Dark", "Chernobyl",],
    },    

    { categoryTitle: 'Expressões',
    categoryList: ["A céu aberto", "Abandonar o barco", "Abotoar o paletó", "Abrir o coração", "Abrir o jogo", "Acabar em pizza", "Acertar na lata", "Acertar na mosca", "Agarrar com unhas e dentes", "Água que passarinho não bebe", "Amarrar o burro", "Amigo da onça", "Andar feito barata tonta", "Andar na linha", "Andar nas nuvens", "Ao pé da letra", "Aos trancos e barrancos", "Armar um barraco", "Arrancar os cabelos", "Arrastar as asas", "Arregaçar as mangas", "Arrumar sarna para se coçar", "Babar ovo", "Baixar a bola", "Banho de gato", "Banho de água fria", "Barata tonta", "Barra pesada", "Bater as botas", "Bater na mesma tecla", "Bater papo", "Bode expiatório", "Botar a boca no trombone", "Cair a ficha", "Cara de pau", "Chutar o balde", "Chutar o pau da barraca", "Colocar melancia na cabeça", "Dar o braço a torcer", "Deixar na mão", "Encher linguiça", "Enfiar o pé na jaca", "Engolir sapo", "Entrar pelo cano", "Enxugar gelo", "Fazer tempestade em copo d’água", "Ir catar coquinho", "Ir desta para melhor", "Ir para o espaço", "Ir pentear macaco", "Ir tomar banho", "Jogado para escanteio", "Lavar a roupa suja", "Lavar as mãos", "Levantar com o pé esquerdo", "Levar ferro", "Levar toco", "Levar um fora", "Mandar ver", "Matar a cobra e mostrar o pau", "Meter o dedo na ferida", "Meter o rabo entre as pernas", "Meter os pés pelas mãos", "Mudar da água para o vinho", "O gato comeu a língua", "Onde Judas perdeu as botas", "Pagar o pato", "Pendurar as chuteiras", "Pensar na morte da bezerra", "Perder a linha", "Perder as estribeiras", "Pirar na batatinha", "Pisar na bola", "Procurar sarna para se coçar", "Procurar uma agulha num palheiro", "Pôr as cartas na mesa", "Pôr minhoca na cabeça", "Pôr mãos à obra", "Pôr os pingos nos “is”", "Puxar saco", "Quebrar o galho", "Receber um balde de água fria",],
    },
    
]